# numpy - numerical python library|

In [4]:
#import numpy library 

import numpy as np


In [5]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr[1][3]

8

In [7]:
#diamension of the array
print(arr.ndim)
print(arr.shape)
print(arr.data)
print(arr.size)
print(type(arr))

2
(2, 4)
8
<class 'numpy.ndarray'>


# lab 1 random number generator using numpy

In [8]:
from numpy import random 
x= random.randint(100,size=7)
x

array([78,  9, 57, 76, 12, 33, 42])

In [9]:
y= random.rand(100)
y

array([0.44966881, 0.19298774, 0.27359878, 0.57378083, 0.13158947,
       0.36711513, 0.87777803, 0.16958605, 0.42403704, 0.55149474,
       0.43610944, 0.15961687, 0.0086258 , 0.97010607, 0.88664959,
       0.78148515, 0.32372023, 0.86093731, 0.94901708, 0.52528985,
       0.09620398, 0.7366852 , 0.02750775, 0.68001945, 0.79009677,
       0.01909317, 0.77865083, 0.70079488, 0.39827457, 0.23074876,
       0.94340667, 0.49595988, 0.94660462, 0.53843048, 0.47180994,
       0.88062531, 0.82758035, 0.64835396, 0.27247788, 0.57658035,
       0.29764853, 0.82707491, 0.3904665 , 0.98557983, 0.81127714,
       0.07697436, 0.23540602, 0.95630677, 0.41446698, 0.44541779,
       0.87971621, 0.96013266, 0.73758423, 0.90354174, 0.53017577,
       0.63856321, 0.44057713, 0.52739095, 0.01272093, 0.647324  ,
       0.74051052, 0.42327803, 0.10909826, 0.87267116, 0.12044078,
       0.51553414, 0.33861416, 0.63728776, 0.54155242, 0.72773   ,
       0.55108996, 0.32988985, 0.49232418, 0.29501031, 0.56398

In [10]:
h= random.random((2,2))
h

array([[0.14509507, 0.74720266],
       [0.05967358, 0.76122867]])

In [11]:
x= random.randint(100,size=(3,3))
random.seed(100)
x

array([[87, 96, 64],
       [93, 31, 26],
       [47, 92, 68]])

In [12]:
y= random.randint(100,size=(3,3))
random.seed(100)
y

array([[ 8, 24, 67],
       [87, 79, 48],
       [10, 94, 52]])

# numpy function 

In [13]:
#zeros matrix/arrays
h = np.zeros((3,3,))
h

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#ones matrix/arrays
h= np.ones((3,3))
h

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#identity matrix

idt = np.eye(3)
idt

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
#create constant matrix 
const = np.full((3,3),5)
const

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# array  indexing and slicing 

In [17]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

a[0][0] a[0][1] a[0][2]

In [18]:
arr[0]

array([1, 2, 3, 4])

In [19]:
arr[1]

array([5, 6, 7, 8])

In [20]:
arr[0][1]=4
arr

array([[1, 4, 3, 4],
       [5, 6, 7, 8]])

In [21]:
#slicing 
#arr[slicing of   row , slicing of coloums]
#arr[st:end , st: end]
arr[0: , 1:2]
arr

array([[1, 4, 3, 4],
       [5, 6, 7, 8]])

In [22]:
arr1 = np.full((3,4),2)
arr1

arr2 = np.full((3,4),6)
arr2

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

# array broadcasting

In [23]:
#addition of matrix
print(arr1+arr2)
print(np.add(arr1,arr2))

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [24]:
#subtract of matrix
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[-4 -4 -4 -4]
 [-4 -4 -4 -4]
 [-4 -4 -4 -4]]
[[-4 -4 -4 -4]
 [-4 -4 -4 -4]
 [-4 -4 -4 -4]]


In [25]:
#multiply 
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]
[[12 12 12 12]
 [12 12 12 12]
 [12 12 12 12]]


In [26]:
#square root
sq=np.sqrt(arr1)
sq

array([[1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356]])

In [27]:
np.sqrt(arr2)

array([[2.44948974, 2.44948974, 2.44948974, 2.44948974],
       [2.44948974, 2.44948974, 2.44948974, 2.44948974],
       [2.44948974, 2.44948974, 2.44948974, 2.44948974]])

In [28]:
np.sum(arr1)

24

In [29]:
np.sum(arr2)

72

In [30]:
np.sum(sq, axis=0)

array([4.24264069, 4.24264069, 4.24264069, 4.24264069])

In [31]:
np.sum(sq, axis=1)

array([5.65685425, 5.65685425, 5.65685425])

In [32]:
np.sum(sq[0], axis=0)

5.656854249492381

# calculate BMI of players

In [33]:
#height of players in inches
height_in =[55,66,60,88,74,70,50,78,79,77,74]
ht_np = np.array(height_in)
#convert into meter
ht_np = ht_np*0.0245
ht_np

array([1.3475, 1.617 , 1.47  , 2.156 , 1.813 , 1.715 , 1.225 , 1.911 ,
       1.9355, 1.8865, 1.813 ])

In [34]:
#weight of players 
weight_pd = [100,120,115,114,120,140,140,200,210,114,110]
wt_np = np.array(weight_pd)

#convert into kg
wt_np = wt_np*0.45
wt_np

array([45.  , 54.  , 51.75, 51.3 , 54.  , 63.  , 63.  , 90.  , 94.5 ,
       51.3 , 49.5 ])

In [35]:
#calculate bmi value
bmi=wt_np/ht_np**2
bmi

array([24.78306215, 20.65255179, 23.94835485, 11.03620737, 16.42850906,
       21.41964658, 41.98250729, 24.64456378, 25.22582957, 14.41463819,
       15.05946664])

In [36]:
bmi[bmi<20]

array([11.03620737, 16.42850906, 14.41463819, 15.05946664])

In [37]:
bmi[bmi>20]

array([24.78306215, 20.65255179, 23.94835485, 21.41964658, 41.98250729,
       24.64456378, 25.22582957])

In [38]:
players= np.array([wt_np,ht_np])
players

array([[45.    , 54.    , 51.75  , 51.3   , 54.    , 63.    , 63.    ,
        90.    , 94.5   , 51.3   , 49.5   ],
       [ 1.3475,  1.617 ,  1.47  ,  2.156 ,  1.813 ,  1.715 ,  1.225 ,
         1.911 ,  1.9355,  1.8865,  1.813 ]])

In [39]:
pT= players.T
pT.shape

(11, 2)

# statical operation

In [44]:
print(np.amax(ht_np))
print(np.amax(wt_np))
print(np.amin(ht_np))
print(np.amin(wt_np))
print(np.corrcoef(ht_np))

2.156
94.5
1.225
45.0
1.0


In [62]:
#boolean
bools = [False, True,True,False,False]
bools
b=np.array(bools)
b

array([False,  True,  True, False, False])

In [63]:
b.sum()

2

In [64]:
b.any()

True

In [65]:
b.all()

False

In [66]:
n = np.array(['b','b','b','c','c','c','d','d','het','het'])
n

array(['b', 'b', 'b', 'c', 'c', 'c', 'd', 'd', 'het', 'het'], dtype='<U3')

In [67]:
np.unique(n)

array(['b', 'c', 'd', 'het'], dtype='<U3')